version: '3'
services:
  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.7.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml  # Mount the configuration file

  grafana:
    image: grafana/grafana:latest # Updated version
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    depends_on:
      - loki
