server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 1h
  chunk_retain_period: 30m
  max_chunk_age: 1h
  lifecycler:
    ring:
      kvstore:
        store: inmemory

storage_config:
  boltdb:
    directory: /loki/index
    retention_policy: 24h

schema_config:
  configs:
    - from: 2020-01-01
      store: boltdb
      object_store: filesystem
      schema: v10
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  retention_delete_delay: 1h

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20

chunks_storage:
  boltdb:
    directory: /loki/chunks

